component: express # (必填) 引用 component 的名称，当前用到的是 express-tencent 组件
name: expressDemo # (必填) 组件创建的实例名称
#组件配置
inputs:
 src:
   src: ./app.js
 region: ap-guangzhou 
# component: express 
# name: my_express
# express:
#   inputs:
#     region: ap-shanghai